servuce:
  - docker
language: python
install: true
git:
  depth: 3
  submodules: true
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - docker build -t saidsef/k8s-spot-termination-notice:latest .
  - docker push saidsef/k8s-spot-termination-notice
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
