dist: xenial
sudo: required
git:
  depth: 3
  submodules: true
branches:
  only:
  - master
  - "/.*/"
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
script:
  - cd function/
  - |
   if [ $TRAVIS_BRANCH == "master" ]; then
     export TAG="latest"
   else
     export TAG=$TRAVIS_BRANCH
   fi
  - docker build -t saidsef/k8s-spot-termination-notice:$TAG
  - docker push saidsef/k8s-spot-termination-notice:$TAG
after_script:
  - docker images
notifications:
  email: true
after_success:
  - echo "All done!"
