dist: xenial
sudo: required
git:
  depth: 3
  submodules: true
branches:
  only:
  - master
  - "/^release-.*$/"
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
script:
  - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t saidsef/k8s-spot-termination-notice:latest --push .
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
