---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-termination-notice
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-termination-notice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-termination-notice
    spec:
      serviceAccountName: spot-termination-notice
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/arch"
                    operator: "In"
                    values:
                      - "amd64"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: spot-termination-notice
        image: k8s-spot-termination-notice
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CLUSTER
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SLACK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: spot-termination-notice
              key: SLACK_API_TOKEN
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: spot-termination-notice
              key: SLACK_CHANNEL
        - name: DRAIN_NODE
          value: "false"
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
              - pgrep
              - python
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
