---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-termination-notice
spec:
  selector:
    matchLabels:
      app: spot-termination-notice
  template:
    metadata:
      labels:
        app: spot-termination-notice
    spec:
      # future proof: create service account for node draining
      # serviceAccountName: spot-termination-notice
      tolerations:
        - key: "kubernetes.io/arch"
          operator: "Equal"
          value: "amd64"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: spot-termination-notice
        image: saidsef/k8s-spot-termination-notice:latest
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPOT_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SLACK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: SLACK_API_TOKEN
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: slack
              key: SLACK_CHANNEL
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 20m
            memory: 20Mi
        livenessProbe:
          exec:
            command:
              - pgrep
              - python
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        lifecycle:
          postStart:
            exec:
              command:
                - pgrep
                - python
