---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yml
- daemonset.yml
- secret.yml

images:
- name: spot-termination-notice
  newName: docker.io/saidsef/k8s-spot-termination-notice
  newTag: v2022.12

commonAnnotations:
  app.kubernetes.io/name: spot-termination-notice
  app.kubernetes.io/part-of: spot-termination-notice
