---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-termination-notice
  labels:
    app: spot-termination-notice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spot-termination-notice
  labels:
    app: spot-termination-notice
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["deployments", "replicaset"]
  verbs: ["get", "watch", "list"]

