---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack
  labels:
    app.kubernetes.io/name: spot-termination-notice
data:
  SLACK_API_TOKEN: "YmFzZTY0LWVuY29kZWQtc2xhY2stdG9rZW4tZ29lcy1oZXJlCg=="
  SLACK_CHANNEL: "YmFzZTY0LWVuY29kZWQtc2xhY2stY2hhbm5lbC1uYW1lLWdvZXMtaGVyZQo="