---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack
  labels:
    name: slack
    app: spot-termination-notice
data:
  SLACK_API_TOKEN: "base64-encoded-slack-token-goes-here"
  SLACK_CHANNEL: "base64-encoded-slack-channel-name-goes-here"